name: task_manager_app
description: Menadżer Zadań 
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter: { sdk: flutter }
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.19.0
  http: ^1.2.2
  geolocator: ^12.0.0
  equatable: ^2.0.5
  flutter_material_color_picker: ^1.2.0
  collection: ^1.18.0
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true